version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dbname
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres_data:
